#!/usr/bin/bash

cp $1.dict.yaml temp.txt

echo "删除 rime 词库头"
sed -i '1,/\.\.\./d' temp.txt

echo "生成 fcitx5 词库"
sed -i "s/ /'/g" temp.txt
sed -i "/^$/d" temp.txt
cat temp.txt | awk '{printf "%s\t%s\t0\n",$1,$2}' > $1.dict.txt

echo "编译 fcitx5 词库"
libime_pinyindict $1.dict.txt $1.dict

echo "删除缓存文件"
rm temp.txt
