#!/usr/bin/zsh
#
# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: Coelacanthus
#
# Copies the contents of the given files (or stdin, if no files are given) to
# the terminal that runs this program.
#
# This is achieved by writing an OSC 52 escape sequence to the said terminal.
# The maximum length of an OSC 52 escape sequence is 100_000 bytes, of which
# 7 bytes are occupied by a "\033]52;c;" header, 1 byte by a "\a" footer, and
# 99_992 bytes by the base64-encoded result of 74_994 bytes of copyable text.
#
# In other words, this program can only copy up to 74_994 bytes of its input.
#
# See http://en.wikipedia.org/wiki/Base64 for the 4*ceil(n/3) length formula.
# See http://sourceforge.net/p/tmux/mailman/message/32221257 for copy limits.
# See http://sourceforge.net/p/tmux/tmux-code/ci/a0295b4c2f6 for DCS in tmux.

buf=$( cat "$@" )
len=$( printf %s "$buf" | wc -c ) max=74994
if (( $len > $max ));then
    echo "$0: input is $(( len - max )) bytes too long" >&2
else
    printf "\033]52;c;%s\a" "$( printf %s "$buf" | head -c "$max" | base64 | tr -d '\r\n' )"
fi

# vim: ft=sh sw=4 ts=8 sts=4 et:
# kate: space-indent on; indent-width 4; syntax bash;
