
[[plugins]]
repo = 'Shougo/context_filetype.vim'

[[plugins]]
repo = 'zchee/deoplete-zsh'
on_ft = ['zsh', 'sh']

# Syntax source for neocomplete/deoplete/ncm
[[plugins]]
repo = 'shougo/neco-syntax'
# Include completion framework for neocomplete/deoplete
[[plugins]]
repo = 'Shougo/neoinclude.vim'


[[plugins]]
repo = 'nvim-treesitter/nvim-treesitter'
if = 'has("nvim")'
on_event = 'BufRead'
hook_source = '''
lua <<EOF
require'nvim-treesitter.configs'.setup {
    highlight = {
        enable = true,
        disable = {},
    },
    incremental_selection = {
        enable = true,
        disable = {},
        keymaps = {
          init_selection = 'gnn',
          node_incremental = 'grn',
          scope_incremental = 'grc',
          node_decremental = 'grm',
        }
    },
    refactor = {
      highlight_defintions = {
        enable = true
      },
      smart_rename = {
        enable = true,
        smart_rename = 'grr'
      },
      navigation = {
        enable = true,
        goto_definition = 'gnd',
        list_definitions = 'gnD'
      }
    },
    ensure_installed = 'all'
}
EOF
'''
