

[[plugins]]
repo = 'wsdjeg/dein-ui.vim'

[[plugins]]
repo = 'Shougo/denite.nvim'
    
[[plugins]]
repo = 'tpope/vim-fugitive'

#""""""""""""""""""""""""" 主题配色
#call dein#add('morhetz/gruvbox')
[[plugins]]
repo = 'joshdick/onedark.vim'
# 状态栏
[[plugins]]
repo = 'vim-airline/vim-airline'
# 状态栏主题
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'lilydjwg/fcitx.vim'

[[plugins]]
repo = 'kassio/neoterm'
# 支持库，给其他插件用的函数库
[[plugins]]
repo = 'xolox/vim-misc'
# 缩进指示线
[[plugins]]
repo = 'Yggdroot/indentLine'
# 自动括号
[[plugins]]
repo = 'jiangmiao/auto-pairs'
# Tagbar
[[plugins]]
repo = 'majutsushi/tagbar'
# 注释插入
[[plugins]]
repo = 'preservim/nerdcommenter'
# 彩虹括号
[[plugins]]
repo = 'luochen1990/rainbow'
# HELP文档中文
[[plugins]]
repo = 'yianwillis/vimcdoc'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'
on_if = '!has("nvim")'

[[plugins]]
repo = 'roxma/nvim-yarp'
on_if = '!has("nvim")'
