format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$cmake\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$golang\
$helm\
$java\
$julia\
$kotlin\
$nim\
$nodejs\
$ocaml\
$perl\
$php\
$purescript\
$python\
$red\
$ruby\
$rust\
$scala\
$swift\
$lua\
$terraform\
$vlang\
$vagrant\
$zig\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$crystal\
$custom\
$shell\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$line_break\
$character"""




[time]
disabled = false

[status]
disabled = false
style = "bold blue"
format = "[$symbol [->](white) [$common_meaning$signal_name](red) $hex_status]($style) "
symbol = "[X](red)"
success_symbol = "[!](green)"
pipestatus = true
pipestatus_format = "\\[ $pipestatus\\] => [$symbol [->](white) [$common_meaning$signal_name](red) $hex_status]($style)"
pipestatus_separator = "| "

[username]
show_always = true
format = "[$user]($style) "

[hostname]
ssh_only = false
format = "@ [$hostname]($style) in "

[character]
success_symbol = "[>>>](bold green)"
error_symbol = "[>>>](bold red)"
vicmd_symbol = "[<<<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[shell]
disabled = false
format = "in [\\[$indicator\\]]($style) "
style = "blue bold"
bash_indicator = "Bash"
fish_indicator = "Fish"
zsh_indicator = "Zsh"
powershell_indicator = "PowerShell"
ion_indicator = "Ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
xonsh_indicator = "Xonsh"
unknown_indicator = "Unknown Shell"

[aws]
symbol = "AWS "

[cobol]
symbol = "Conda "

[conda]
symbol = "COBOL "

[crystal]
symbol = "Crystal "

[cmake]
symbol = "CMake "

[dart]
symbol = "Dart "

[deno]
symbol = "Deno "

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"
truncation_length = 5
truncate_to_repo = false

[docker_context]
symbol = "docker "

[elixir]
symbol = "elixir "

[elm]
symbol = "elm "

[erlang]
symbol = "Erlang "

[git_branch]
symbol = "git "

[golang]
symbol = "Go "

[hg_branch]
symbol = "hg "

[java]
symbol = "Java "

[julia]
symbol = "julia "

[kotlin]
symbol = "Kotlin "

[lua]
symbol = "Lua "

[nodejs]
symbol = "NodeJS "

[memory_usage]
symbol = "Memory "

[nim]
symbol = "Nim "

[nix_shell]
symbol = "Nix "

[ocaml]
symbol = "OCaml "

[package]
symbol = "pkg "

[perl]
symbol = "Perl "

[php]
symbol = "PHP "

[purescript]
symbol = "PureScript "

[python]
symbol = "Python "

[rlang]
symbol = "R "

[ruby]
symbol = "Ruby "

[rust]
symbol = "Rust "

[scala]
symbol = "Scala "

[swift]
symbol = "Swift "

