format = """
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$vcsh\
$git_branch\
$git_commit\
$git_state\
$git_status\
$hg_branch\
$docker_context\
$package\
$dotnet\
$nodejs\
$python\
$red\
$rust\
$terraform\
$vagrant\
$nix_shell\
$conda\
$memory_usage\
$aws\
$gcloud\
$openstack\
$env_var\
$custom\
$shell\
$cmd_duration\
$jobs\
$battery\
$time\
$status\
$line_break\
$character"""


continuation_prompt = "[>>>](bold yellow) "

[aws]
symbol = "AWS "

[battery]
format = "[Battery $percentage]($style) "

[character]
success_symbol = "[>>>](bold green)"
error_symbol = "[>>>](bold red)"
vicmd_symbol = "[<<<](bold green)"

[cobol]
symbol = "Conda "

[conda]
symbol = "COBOL "

[container]
disabled = true

[crystal]
symbol = "Crystal "
disabled = true

[cmake]
symbol = "CMake "
disabled = true

[dart]
symbol = "Dart "
disabled = true

[deno]
symbol = "Deno "
disabled = true

[dotnet]
symbol = ".NET "

[directory]
read_only = " ro"
truncation_length = 4
truncate_to_repo = false
# using fish style path truncation
fish_style_pwd_dir_length = 1
# using logical path insetad of resolving symbol link 
use_logical_path = true

[docker_context]
symbol = "docker "

[elixir]
symbol = "elixir "
disabled = true

[elm]
symbol = "elm "
disabled = true

[erlang]
symbol = "Erlang "
disabled = true

[gcloud]
symbol = "GoogleCloud "

[git_branch]
symbol = "git "

[git_commit]
commit_hash_length = 8
tag_symbol = " tag "

[git_status]
format = '([\[ $all_status[|](purple) $ahead_behind \]]($style) )'
# ASCII
#ahead = "[>${count}](green)"
#behind = "[<${count}](red)"
#diverged = "[<${behind_count}](red)[>${ahead_count}](green)"
#untracked = "?${count} "
#stashed = "$${count} "
#modified = "[!${count}](blue) "
#staged = '[++\($count\)](green) '
#renamed = "[R${count}](yellow) "
#deleted = "[x${count}](red) "
# Unicode
ahead = "[↑${count}](green)"
behind = "[↓${count}](red)"
diverged = "⇕[↑${ahead_count}](green)[↓${behind_count}](red)"
untracked = "?${count} "
stashed = "$${count} "
modified = "[!${count}](blue) "
staged = '[++\($count\)](green) '
renamed = "[R${count}](yellow) "
deleted = "[✘${count}](red) "

[golang]
symbol = "Go "
disabled = true

[helm]
symbol = "Helm "
disabled = true

[hg_branch]
symbol = "hg "

[hostname]
ssh_only = false
format = "@ [$hostname]($style) in "

[java]
symbol = "Java "
disabled = true

[julia]
symbol = "julia "
disabled = true

[kotlin]
symbol = "Kotlin "
disabled = true

[kubernetes]
symbol = "k8s "

[lua]
symbol = "Lua "
disabled = true

[nodejs]
symbol = "NodeJS "

[memory_usage]
symbol = "Memory "

[nim]
symbol = "Nim "
disabled = true

[nix_shell]
symbol = "Nix "

[ocaml]
symbol = "OCaml "
disabled = true

[openstack]
symbol = "OpenStack "

[package]
symbol = "pkg "

[perl]
symbol = "Perl "
disabled = true

[php]
symbol = "PHP "
disabled = true

[pulumi]
symbol = "Pulumi "

[purescript]
symbol = "PureScript "
disabled = true

[python]
symbol = "Python "

[rlang]
symbol = "R "
disabled = true

[ruby]
symbol = "Ruby "
disabled = true

[rust]
symbol = "Rust "

[scala]
symbol = "Scala "
disabled = true

[shell]
disabled = false
format = "in [\\[$indicator\\]]($style) "
style = "blue bold"
bash_indicator = "Bash"
fish_indicator = "Fish"
zsh_indicator = "Zsh"
powershell_indicator = "PowerShell"
ion_indicator = "Ion"
elvish_indicator = "elvish"
tcsh_indicator = "tcsh"
xonsh_indicator = "Xonsh"
cmd_indicator = "CMD"
nu_indicator = "NuShell"
unknown_indicator = "Unknown Shell"

[status]
disabled = false
style = "bold blue"
format = "[$symbol [->](white) [$common_meaning$signal_name](red) $hex_status]($style) "
symbol = "[X](red)"
success_symbol = "[!](green)"
pipestatus = true
pipestatus_format = "\\[ $pipestatus\\] => [$symbol [->](white) [$common_meaning$signal_name](red) $hex_status]($style)"
pipestatus_separator = "| "

[sudo]
symbol = "sudo "

[swift]
symbol = "Swift "
disabled = true

[terraform]
symbol = "Terraform "

[time]
disabled = false

[username]
show_always = true
format = "[$user]($style) "

[vagrant]
symbol = "Vagrant "

[vlang]
disabled = true

[zig]
symbol = "Zig "
disabled = true
