# Use lualatex with latexmk.
# $pdf_mode = 4;

# Use xelatex with latexmk.
$pdf_mode = 5;

$pdflatex = "pdflatex -interaction=nonstopmode -synctex=1 %O %S";
$xelatex = "xelatex -shell-escape -file-line-error -halt-on-error -interaction=nonstopmode -no-pdf -synctex=1 %O %S";
$xdvipdfmx = "xdvipdfmx -E -o %D %O %S";

$pdf_previewer = "okular"

# vim: set ft=perl:
# kate: space-indent on; indent-width 4; syntax perl;
