# SPDX-License-Identifier: MPL-2.0
# SPDX-FileCopyrightText: Coelacanthus

[[plugins]]
repo = 'vim-denops/denops.vim'
if = "executable('deno')"

#[[plugins]]
#repo = 'yegappan/lsp'
#name = 'vim9lsp'

[[plugins]]
repo = 'prabirshrestha/vim-lsp'

[[plugins]]
repo = 'mattn/vim-lsp-settings'
depends = ['vim-lsp']

[[plugins]]
repo = 'majutsushi/tagbar'
if = "executable('ctags')"
depends = ['gtags.vim', 'vim-gutentags']

[[plugins]]
repo = 'dense-analysis/ale'
#on_ft = ['sh', 'c', 'cpp', 'rust', 'python', 'go', 'tex']

[[plugins]]
repo = 'vim-scripts/gtags.vim'
if = "executable('gtags') || executable('ctags')"

[[plugins]]
repo = 'ludovicchabant/vim-gutentags'
if = "executable('gtags') || executable('ctags')"

[[plugins]]
repo = 'rrethy/vim-hexokinase'
if = "executable('go')"
build = 'make hexokinase'

[[plugins]]
repo = 'roxma/nvim-yarp'

[[plugins]]
repo = 'roxma/vim-hug-neovim-rpc'

[[plugins]]
repo = 'dstein64/vim-startuptime'
on_cmd = 'StartupTime'

[[plugins]]
repo = 'rhysd/vim-healthcheck'
on_cmd = 'CheckHealth'

[[plugins]]
repo = 'mattn/webapi-vim'

[[plugins]]
repo = 'mattkretz/vim-gnuindent'
on_cmd = 'SetupGnuIndent'

[[plugins]]
repo = 'inkarkat/vim-mark'
on_cmd = 'Mark'

# vim: set sw=4 ts=8 sts=4 et foldmethod=marker:
# kate: space-indent on; indent-width 4; syntax toml;
